### \u670D\u52A1\u7AEF\u53E3\u53F7
server:
  port: 8205
spring:
  application:
    name: consul-member
  ####consul\u6CE8\u518C\u4E2D\u5FC3\u5730\u5740
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        service-name: consul-member2