server:
  port: 8100
spring:
  application:
    name: eurekaserver
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8101/eureka/,http://localhost:8102/eureka/
    fetch-registry: true
    register-with-eureka: true