### 端口
server:
  port: 8204
spring:
  application:
    name: consul-member
  ####注册地址
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        service-name: consul-member1

